return json instead of rending the page
cuongtran-6618/weather-app pull request #5
Opened 2021-06-28 09:10 UTC by cuong-tran-solteq

#4 WEA-1

2021-06-29 13:39 UTC, zuanoc requested changes

2021-06-29 13:39 UTC, zuanoc commented on controllers/weather.js
> +    if (!city || "" === city)
cai nay chi can `if(!city)` la du roi Cuong oi

2021-06-29 13:39 UTC, zuanoc commented on controllers/weather.js
> +    {
coding style cua js la 

```
if(condition) {
  ...
}
```

2021-06-29 13:39 UTC, zuanoc commented on controllers/weather.js
> +        res.send({
res.send la de send success reponse. Trong truong hop nay, minh phai them error status (trong truong hop nay la 400) thi moi response error

2021-06-29 13:39 UTC, zuanoc commented on controllers/weather.js
> +            "message": "error"
- neu viet code js thi minh thuong ko can quote cho object key, trong truong hop nay {message : "..."} la ok roi
- minh co the the thong tin chi tiet cho message `"error"` de nguoi dung api biet duoc loi j

2021-06-29 13:39 UTC, zuanoc commented on controllers/weather.js
> +
doan code nay bi lap lai nen minh co the extract no ra 1 function roi dung

2021-06-29 13:39 UTC, zuanoc commented on controllers/weather.js
> +    if (!city || " " === city)
`" "` hay `""`? 😛

2021-06-29 13:40 UTC, zuanoc commented on controllers/weather.js
> +    if (!city || "" === city)
ong co the tham khao coding style o day nhe: https://github.com/airbnb/javascript.

2021-07-01 10:53 UTC, cuongtran-6618 commented on controllers/weather.js
> +    if (!city || " " === city)
:))) bị ám ảnh bên php khi user nó oánh cái space trong url, mà sửa lại với trim nên không cần cái đó nữa

2021-07-01 10:53 UTC, cuongtran-6618 commented on controllers/weather.js
> +        res.send({
👍🏻  Yeah cam ơn ong tôi sửa lại cái đó rồi.

2021-07-01 11:01 UTC, cuongtran-6618 commented on services/weather.js
> +        return false;
@zuanoc có cách nào handler error tốt hơn không ông? 
Lúc trước làm tôi return nguyên cái error này lên controller. Nhung nó k catch được trên đó mà chỉ có undefine ở cái result t có tìm mà chưa thấy. T thấy 1 số repo khác nó k dùng controller thì nó catch error ngay trên router. Như bên ông thì handler kiểu gì? NEST support luôn hả

2021-07-04 19:02 UTC, zuanoc commented on services/weather.js
> +        return false;
1. vi sao minh ko merge cai `fetchWeatherData` vao ham` fetchWeatherDataByCity? 
2. hien co 2 cach toi co the nghi den de handle cai error nay:
  - define custom error 
  - tra ve result voi error code nhu: 
  
```
{
  success: boolean
  errorCode: string
  result: any
}
```

2021-07-04 19:04 UTC, zuanoc commented on controllers/weather.js
> +    {
toi add cai task nay de improve coding style + auto code format: https://github.com/cuongtran-6618/weather-app/projects/1#card-64346730

2021-07-04 19:05 UTC, zuanoc commented on controllers/weather.js
> +        res.send({
yay

2021-07-04 19:35 UTC, zuanoc approved these changes
Good job!

2021-07-04 19:36 UTC, zuanoc commented
@cuongtran-6618 oi, ong cu merge cai PR nay nhe. Cai error handling thi ong lam o cai PR https://github.com/cuongtran-6618/weather-app/pull/6 nhe. Thanks

2021-07-04 19:42 UTC, cuongtran-6618 commented
> @cuongtran-6618 oi, ong cu merge cai PR nay nhe. Cai error handling thi ong lam o cai PR #6 nhe. Thanks

Yeah cam on ong review nha :D

2021-07-04 19:42 UTC, merged